const chapters = [
    {
      label: "Chapter 4",
      seasons: [
        {
          season: "4",
          lasted: "70 days",
          published: "2023-11-03",
          link: "",
          image: "/assets/chapters/chapter-4-4.jpg",
        },
        {
          season: "3",
          lasted: "77 days",
          published: "2023-08-25",
          link: "",
          image: "/assets/chapters/chapter-4-3.jpg",
        },
        {
          season: "2",
          lasted: "91 days",
          published: "2023-06-09",
          link: "",
          image: "/assets/chapters/chapter-4-2.jpg",
        },
        {
          season: "1",
          lasted: "96 days",
          published: "2023-03-10",
          link: "",
          image: "/assets/chapters/chapter-4-1.jpg",
        },
      ],
    },
    {
      label: "Chapter 3",
      seasons: [
        {
          season: "4",
          lasted: "77 days",
          published: "2022-12-04",
          link: "",
          image: "/assets/chapters/chapter-3-4.jpg",
        },
        {
          season: "3",
          lasted: "105 days",
          published: "2022-09-18",
          link: "",
          image: "/assets/chapters/chapter-3-3.jpg",
        },
        {
          season: "2",
          lasted: "77 days",
          published: "2022-06-05",
          link: "",
          image: "/assets/chapters/chapter-3-2.jpg",
        },
        {
          season: "1",
          lasted: "105 days",
          published: "2022-03-20",
          link: "",
          image: "/assets/chapters/chapter-3-1.jpg",
        },
      ],
    },
    {
      label: "Chapter 2",
      seasons: [
        {
          season: "8",
          lasted: "83 days",
          published: "2021-12-05",
          link: "",
          image: "/assets/chapters/chapter-2-8.jpg",
        },
        {
          season: "7",
          lasted: "94 days",
          published: "2021-09-13",
          link: "",
          image: "/assets/chapters/chapter-2-7.jpg",
        },
        {
          season: "6",
          lasted: "84 days",
          published: "2021-06-08",
          link: "",
          image: "/assets/chapters/chapter-2-6.jpg",
        },
        {
          season: "5",
          lasted: "104 days",
          published: "2021-03-16",
          link: "",
          image: "/assets/chapters/chapter-2-5.jpg",
        },
        {
          season: "4",
          lasted: "97 days",
          published: "2020-12-02",
          link: "",
          image: "/assets/chapters/chapter-2-4.jpg",
        },
        {
          season: "3",
          lasted: "71 days",
          published: "2020-08-27",
          link: "",
          image: "/assets/chapters/chapter-2-3.jpg",
        },
        {
          season: "2",
          lasted: "118 days",
          published: "2020-06-17",
          link: "",
          image: "/assets/chapters/chapter-2-2.jpg",
        },
        {
          season: "1",
          lasted: "128 days",
          published: "2020-02-20",
          link: "",
          image: "/assets/chapters/chapter-2-1.jpg",
        },
      ],
    },
    {
      label: "Chapter 1",
      seasons: [
        {
          season: "x",
          lasted: "73 days",
          published: "2019-10-03",
          link: "",
          image: "/assets/chapters/chapter-1-x.jpg",
        },
        {
          season: "9",
          lasted: "84 days",
          published: "2019-08-01",
          link: "",
          image: "/assets/chapters/chapter-1-9.jpg",
        },
        {
          season: "8",
          lasted: "70 days",
          published: "2019-03-09",
          link: "",
          image: "/assets/chapters/chapter-1-8.jpg",
        },
        {
          season: "7",
          lasted: "84 days",
          published: "2019-02-28",
          link: "",
          image: "/assets/chapters/chapter-1-7.jpg",
        },
        {
          season: "6",
          lasted: "70 days",
          published: "2018-12-06",
          link: "",
          image: "/assets/chapters/chapter-1-6.jpg",
        },
        {
          season: "5",
          lasted: "78 days",
          published: "2018-09-27",
          link: "",
          image: "/assets/chapters/chapter-1-5.jpg",
        },
        {
          season: "4",
          lasted: "71 days",
          published: "2018-07-11",
          link: "",
          image: "/assets/chapters/chapter-1-4.jpg",
        },
        {
          season: "3",
          lasted: "68 days",
          published: "20-04-01",
          link: "",
          image: "/assets/chapters/chapter-1-3.jpg",
        },
        {
          season: "2",
          lasted: "70 days",
          published: "2018-02-22",
          link: "",
          image: "/assets/chapters/chapter-1-2.jpg",
        },
        {
          season: "1",
          lasted: "51 days",
          published: "2017-12-14",
          link: "",
          image: "/assets/chapters/chapter-1-1.jpg",
        },
      ],
    },
  ];
  